import { describe, it, expect } from "vitest";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { LEGACY_RULES, type RuleDef } from "@/lib/regulatory-graph";

/**
 * Generator + drift guard for the regulatory_rules seed migration.
 *
 * The TS LEGACY_RULES array is the single source of truth for the runtime
 * seed engine. The SQL migration `20260516000005_regulatory_rules_seed.sql`
 * mirrors the same rows into Postgres so the admin tools (and Workstream B
 * corrections loop) can read and edit them. To keep them in sync without
 * hand-maintaining two copies, this spec generates the SQL on demand from
 * LEGACY_RULES and otherwise asserts the committed SQL matches.
 *
 * Regenerate after changing LEGACY_RULES:
 *
 *   WRITE_SEED=1 npm test -- src/__tests__/lib/regulatory-graph-seed.test.ts
 *
 * The drift assertion compares every rule's id + rule_key + name_template
 * against the SQL. A mismatch is a hard fail — fix LEGACY_RULES or
 * regenerate.
 */

const MIGRATION_PATH = resolve(
  __dirname,
  "../../../supabase/migrations/20260516000005_regulatory_rules_seed.sql"
);

function sqlString(s: string | null | undefined): string {
  if (s === null || s === undefined) return "null";
  return "'" + s.replace(/'/g, "''") + "'";
}

function sqlJsonb(obj: unknown): string {
  return "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb";
}

function generateMigration(rules: RuleDef[]): string {
  const header = `-- Workstream A: seed the regulatory_rules table from the TS LEGACY_RULES
-- canonical set. This migration is generated by
-- src/__tests__/lib/regulatory-graph-seed.test.ts — do not edit by hand.
-- Regenerate with: WRITE_SEED=1 npm test -- src/__tests__/lib/regulatory-graph-seed.test.ts
--
-- The TS rule set in src/lib/regulatory-graph.ts is the runtime source of
-- truth for new-business seeding; this migration mirrors the same rows into
-- the DB so admin tooling at /admin/rules and the Workstream B corrections
-- loop have something to read, edit, and propose changes against. Every
-- rule shares a stable UUID across TS + SQL so deadlines.regulatory_rule_id
-- can join cleanly.

`;

  const inserts: string[] = [];
  for (const r of rules) {
    const cols = [
      sqlString(r.id),
      sqlString(r.jurisdiction_type),
      sqlString(r.jurisdiction_code),
      r.industry_slug ? sqlString(r.industry_slug) : "null",
      sqlString(r.rule_key),
      sqlString(r.name_template),
      sqlString(r.description_template),
      sqlString(r.deadline_type),
      sqlString(r.agency_template),
      sqlString(r.frequency),
      sqlJsonb(r.due_date_rule),
      sqlJsonb(r.applies_when),
      sqlString(r.severity_tier),
      r.penalty_estimate_cents === null ? "null" : String(r.penalty_estimate_cents),
      sqlString(r.source_url),
      sqlString(r.statute_citation),
      String(r.rule_version),
    ].join(", ");

    inserts.push(
      `insert into public.regulatory_rules (
  id, jurisdiction_type, jurisdiction_code, industry_slug, rule_key,
  name, description, deadline_type, governing_agency, frequency,
  due_date_rule, applies_when, severity_tier, penalty_estimate_cents,
  source_url, statute_citation, version
) values (${cols})
on conflict (jurisdiction_code, industry_slug, rule_key, version) do update set
  name = excluded.name,
  description = excluded.description,
  deadline_type = excluded.deadline_type,
  governing_agency = excluded.governing_agency,
  frequency = excluded.frequency,
  due_date_rule = excluded.due_date_rule,
  applies_when = excluded.applies_when,
  severity_tier = excluded.severity_tier,
  penalty_estimate_cents = excluded.penalty_estimate_cents,
  source_url = excluded.source_url,
  statute_citation = excluded.statute_citation;`
    );

    inserts.push(
      `insert into public.regulatory_rule_sources (rule_id, source_kind, source_ref)
  select ${sqlString(r.id)}::uuid, 'seed', null
  where not exists (
    select 1 from public.regulatory_rule_sources
    where rule_id = ${sqlString(r.id)}::uuid and source_kind = 'seed'
  );`
    );
  }

  return header + inserts.join("\n\n") + "\n";
}

const expected = generateMigration(LEGACY_RULES);

describe("regulatory_rules seed migration", () => {
  if (process.env.WRITE_SEED === "1") {
    it("(WRITE_SEED) regenerates the migration file", () => {
      writeFileSync(MIGRATION_PATH, expected, "utf8");
      expect(existsSync(MIGRATION_PATH)).toBe(true);
    });
    return;
  }

  if (process.env.APPLY_SEED === "1") {
    it("(APPLY_SEED) upserts every rule into Supabase", async () => {
      const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
      const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
      if (!url || !key) {
        throw new Error(
          "APPLY_SEED requires NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in env."
        );
      }
      const supabase = createClient(url, key, {
        auth: { autoRefreshToken: false, persistSession: false },
      });
      const ruleRows = LEGACY_RULES.map((r) => ({
        id: r.id,
        jurisdiction_type: r.jurisdiction_type,
        jurisdiction_code: r.jurisdiction_code,
        industry_slug: r.industry_slug,
        rule_key: r.rule_key,
        name: r.name_template,
        description: r.description_template,
        deadline_type: r.deadline_type,
        governing_agency: r.agency_template,
        frequency: r.frequency,
        due_date_rule: r.due_date_rule,
        applies_when: r.applies_when,
        severity_tier: r.severity_tier,
        penalty_estimate_cents: r.penalty_estimate_cents,
        source_url: r.source_url,
        statute_citation: r.statute_citation,
        version: r.rule_version,
      }));
      const BATCH = 20;
      let upserted = 0;
      for (let i = 0; i < ruleRows.length; i += BATCH) {
        const { error } = await supabase
          .from("regulatory_rules")
          .upsert(ruleRows.slice(i, i + BATCH), {
            onConflict: "jurisdiction_code,industry_slug,rule_key,version",
          });
        if (error) throw new Error(`Batch failed: ${error.message}`);
        upserted += Math.min(BATCH, ruleRows.length - i);
      }
      expect(upserted).toBe(LEGACY_RULES.length);

      // Provenance: only insert seed-rows that don't already exist.
      const { data: existing } = await supabase
        .from("regulatory_rule_sources")
        .select("rule_id")
        .eq("source_kind", "seed");
      const existingIds = new Set(
        (existing ?? []).map((r: { rule_id: string }) => r.rule_id)
      );
      const newProv = LEGACY_RULES.filter((r) => !existingIds.has(r.id)).map(
        (r) => ({ rule_id: r.id, source_kind: "seed", source_ref: null })
      );
      if (newProv.length > 0) {
        const { error: provError } = await supabase
          .from("regulatory_rule_sources")
          .insert(newProv);
        if (provError) throw new Error(`Provenance insert failed: ${provError.message}`);
      }

      // Sanity: round-trip count.
      const { count } = await supabase
        .from("regulatory_rules")
        .select("*", { count: "exact", head: true });
      expect(count).toBeGreaterThanOrEqual(LEGACY_RULES.length);
    }, 60_000);
    return;
  }

  it("the committed SQL is in sync with LEGACY_RULES", () => {
    if (!existsSync(MIGRATION_PATH)) {
      throw new Error(
        `Missing ${MIGRATION_PATH}. Run with WRITE_SEED=1 to generate.`
      );
    }
    const actual = readFileSync(MIGRATION_PATH, "utf8");
    if (actual !== expected) {
      throw new Error(
        "regulatory_rules seed SQL is out of date. " +
          "Regenerate with: WRITE_SEED=1 npm test -- src/__tests__/lib/regulatory-graph-seed.test.ts"
      );
    }
    expect(actual).toBe(expected);
  });

  it("every LEGACY_RULES rule_key is mentioned in the SQL", () => {
    const sql = existsSync(MIGRATION_PATH) ? readFileSync(MIGRATION_PATH, "utf8") : "";
    for (const r of LEGACY_RULES) {
      expect(sql).toContain(`'${r.rule_key}'`);
      expect(sql).toContain(`'${r.id}'`);
    }
  });
});
